### ISSUE TITLE
MogoDB setting is not picked up by the startup Script

### ISSUE THREAD

**Issue by 123dev** [Graylog2/omnibus-graylog2#30] opened 2016-06-23 16:26 UTC
I initially raised the issue [here](https://github.com/Graylog2/graylog2-server/issues/2370) for Graylog-Server
Then was advised by Marius [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/graylog2/UQVJL0ZidUI/WI1hLbb9CQAJ) to log a omnibus-graylog2 ticket.

I'll summarize the issue here, but the full details and discussion can be checked in the above referenced links.

Even though in graylog.conf we have this setting
`mongodb_uri = mongodb://10.20.1.229:27017/graylog`

The script at
`/opt/graylog/service/graylog-server/run`
is starting the watchdog to localhost mongodb and waiting 10 minutes effectivly delaying the startup of the server.

```
#!/bin/sh
exec 2>&1

umask 077

if [ -f "/opt/graylog/embedded/share/graylog/installation-source.sh" ]; then
    . "/opt/graylog/embedded/share/graylog/installation-source.sh"
fi

export JAVA_HOME=/opt/graylog/embedded/jre
export GRAYLOG_SERVER_JAVA_OPTS="-Xms1g -Xmx1500m -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow"

# check if mongodb is up
timeout 600 bash -c "until curl -s http://127.0.0.1:27017; do sleep 1; done"
exec chpst -P -U graylog -u graylog /opt/graylog/embedded/bin/authbind $JAVA_HOME/bin/java $GRAYLOG_SERVER_JAVA_OPTS -jar -Dlog4j.configurationFile=file:///opt/graylog/conf/log4j2.xml -Djava.library.path=/opt/graylog/server/lib/sigar/ -Dgraylog2.installation_source=${GRAYLOG_INSTALLATION_SOURCE:=unknown} /opt/graylog/server/graylog.jar server -f /opt/graylog/conf/graylog.conf

```

Changing 127.0.0.1 to the address of the primary MongoDB fixes the issue.
It would be best if this script used the value defined in graylog.conf to avoid such problems.

Thanks

**Comment by mariussturm** [comment] 2016-06-24 09:26
Hi,
how did you change the `mongodb_uri` in the graylog.conf file? By hand or via Chef?
The problem is that we can't just use the same value because the `mongodb_uri` can also be a cluster configuration, like `mongodb://host1,host2,host3` which will fail with curl.

**Comment by 123dev** [comment] 2016-06-24 13:15
Hi Marius

We had followed the docs back when we were setting up AWS image based VMs on version 1.x

I believe this command added it to the graylong.conf
`sudo graylog-ctl set-cluster-master <ip-of-vm1>`

Or it could have been done manually (don't really remember)

Basically we have two Graylog servers,
vm1 and vm2
vm1 setup as master running (elasticsearch, etcd, graylog-server, mongodb, nginx)
vm2 running (elasticsearch, etcd, graylog-server, nginx)
and we have two additional datanode servers vm3 and vm4
both running (elasticsearch only)
All of the above in a private Subnet with a publicly accessible ELB pointing to vm1 and vm2 

Seeing in your notes that we can have a cluster configuration for mongodb, we much rather have mongodb running on vm2 as well, for failover / clustering.

Would it be enough to set on both vm1 and vm2 graylog.conf the following setting

`mongodb_uri = mongodb://10.20.1.229:27017/graylog,mongodb://10.20.2.229:27017/graylog`

is the format correct?
And of course make sure that /etc/graylog/graylog-services.json has set
```
  "mongodb": {
    "enabled": true
  }
```

with the current settings when vm1 is down, vm2 does not have access to mongodb and effectively the graylog server is not accessible.

I'm expecting that if we make the change, then it won't be an issue.

Thanks

**Comment by mariussturm** [comment] 2016-06-24 13:35
You can't just put in the the two IPs. First you need to setup a working replicaset. This is not so easy to automate, that's why it's not included in the appliances. You can follow the instructions here: https://docs.mongodb.com/manual/tutorial/deploy-replica-set/

For the appliances we made it a requirement to have a single MongoDB on localhost. Otherwise `graylog-ctl` would not work in the way it is today. If you really need a replicaset please use our Chef or Puppet modules. There you can customize every single Graylog setting.

Closing this as it is working as designed.

**Closed by mariussturm** 2016-06-24 13:35 UTC

**Comment by 123dev** [comment] 2016-06-24 14:19
Thanks Marius,
We'll definitely consider your advise as it sounds to be the right choice moving forward.

Is it easy to migrate from the current setup to a chef setup?
Are there any documents that show us how to convert AWS image based setup to a chef based one?
even at a high level.
I'm afraid setting up from scratch is definitely not an option.

Thanks

**Comment by 123dev** [comment] 2016-06-24 16:19
Followed the replica set instructions
and I believe the replicas are set correctly

I have also modified the startup scripts to include the `--replSet rs0`
`/opt/graylog/mongodb/bin/mongod --dbpath /var/opt/graylog/data/mongodb --smallfiles --replSet rs0`

Here is the `rs.status()`

```
{
        "set" : "rs0",
        "date" : ISODate("2016-06-24T16:00:57.772Z"),
        "myState" : 1,
        "term" : NumberLong(5),
        "heartbeatIntervalMillis" : NumberLong(2000),
        "members" : [
                {
                        "_id" : 0,
                        "name" : "graylog-server1:27017",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                        "uptime" : 1065,
                        "optime" : {
                                "ts" : Timestamp(1466784057, 12),
                                "t" : NumberLong(5)
                        },
                        "optimeDate" : ISODate("2016-06-24T16:00:57Z"),
                        "electionTime" : Timestamp(1466783379, 1),
                        "electionDate" : ISODate("2016-06-24T15:49:39Z"),
                        "configVersion" : 2,
                        "self" : true
                },
                {
                        "_id" : 1,
                        "name" : "graylog-server2:27017",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 684,
                        "optime" : {
                                "ts" : Timestamp(1466784056, 3),
                                "t" : NumberLong(5)
                        },
                        "optimeDate" : ISODate("2016-06-24T16:00:56Z"),
                        "lastHeartbeat" : ISODate("2016-06-24T16:00:56.168Z"),
                        "lastHeartbeatRecv" : ISODate("2016-06-24T16:00:56.145Z"),
                        "pingMs" : NumberLong(0),
                        "syncingTo" : "graylog-server1:27017",
                        "configVersion" : 2
                }
        ],
        "ok" : 1
}
```


But no matter what I do, first instance for graylog-server (either vm1 or vm2), works
the second instance generates the following error. (order does not matter)
And I'm unable to see more than one node in the Web portal.

The error is this.
```
2016-06-24_16:09:31.56897 2016-06-24 16:09:31,568 INFO : org.mongodb.driver.cluster - No server chosen by WritableServerSelector from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=SINGLE, all=[ServerDescription{address=graylog-server2:27017, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 5]}, minWireVersion=0, maxWireVersion=4, maxDocumentSize=16777216, roundTripTimeNanos=793919, setName='rs0', canonicalAddress=graylog-server2:27017, hosts=[graylog-server1:27017, graylog-server2:27017], passives=[], arbiters=[], primary='graylog-server1:27017', tagSet=TagSet{[]}, electionId=null, setVersion=2}]}. Waiting for 30000 ms before timing out
```

I'm suspecting that it might have something to do with
'connectionMode=SINGLE' but am not sure and can't figure out where this is set and how it can be overwritten.

Any guidance is greatly appreciated.
